apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-full-backup
  namespace: velero
spec:
  schedule: "0 2 * * *" # Daily at 2:00 AM
  template:
    includedNamespaces:
    - dhakacart
    includeClusterResources: true
    ttl: 720h # Keep for 30 days
    storageLocation: default
