apiVersion: v1
kind: Service
metadata:
  name: dhakacart-backend
  namespace: default
spec:
  selector:
    app: dhakacart-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
