apiVersion: v1
kind: Service
metadata:
  name: dhakacart-frontend
  namespace: default
spec:
  selector:
    app: dhakacart-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use LoadBalancer for Minikube/Local, change to NodePort or ClusterIP+Ingress for AWS
